http {
	limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/m;

   	upstream backend_servers {
       	server backend1.example.com;
       	server backend2.example.com;
       	server backend3.example.com;
   	}

  	 server {
       	listen 80;

      	 location / {

      		 limit_req zone=mylimit burst=9 nodelay; # burst + nodelay позволят нам пропустить запросы в случае, если у нас было 10 запросов в первую секунду
      		 limit_req_status 429;					 # если же это неважно, то эти опции можно убрать, и будет 10 запросов в минуту, но "растянуто"
													 # как я понял, 10 токенов за 60 сек = 1 запрос в 6 сек
          	 proxy_pass http://backend_servers;
       	}
   }
}
